#!/usr/bin/env bash

# Colors and Symbols
RED=$(printf '\033[0;31m')
GREEN=$(printf '\033[0;32m')
YELLOW=$(printf '\033[1;33m')
BLUE=$(printf '\033[0;34m')
NC=$(printf '\033[0m') # No Color

# Suits
HEARTS="♥"
DIAMONDS="♦"
SPADES="♠"
CLUBS="♣"

# UI Symbols
BOX_TL="╔"
BOX_TR="╗"
BOX_BL="╚"
BOX_BR="╝"
BOX_H="═"
BOX_V="║"
BOX_T_H="╦"
BOX_B_H="╩"
BOX_L_V="╠"
BOX_R_V="╣"
BOX_C_V="╫"
BOX_L_V_THIN="╟"
BOX_R_V_THIN="╢"
BOX_H_THIN="─"

# Bandit Symbols
BANDIT_SYMBOLS=("♣" "●" "✖" "★" "♦" "7")
BANDIT_CLOVER="♣"
BANDIT_CIRCLE="●"
BANDIT_CROSS="✖"
BANDIT_STAR="★"
BANDIT_DIAMOND_SYM="♦"
BANDIT_SEVEN="7"

# Localization
declare -A TXT
TXT[saloon_name]="SMART STAKE SALOON"
TXT[welcome_msg]="Willkommen im 'Smart Stake Saloon'. Setz dich."
TXT[dealer_name]="Luca"
TXT[label_balance]="Guthaben"
TXT[label_bet]="Einsatz"
TXT[label_max]="Max"
TXT[label_wins]="Siege"
TXT[label_losses]="Niederlagen"
TXT[label_pushes]="Unentschieden"
TXT[label_pot]="Pot"
TXT[label_dealer]="DEALER"
TXT[label_your_hand]="DEINE KARTEN"
TXT[label_community]="GEMEINSCHAFTSKARTEN"
TXT[label_your_whiskey]="DEIN WHISKEY"
TXT[label_status]="Status"
TXT[label_dealer_value]="Dealer Wert"
TXT[label_your_value]="Dein Wert"
TXT[label_unknown]="???"
TXT[whiskey_0]="Brandbeschleuniger"
TXT[whiskey_1]="Betrunken"
TXT[whiskey_2]="Leicht beschwipst"
TXT[whiskey_3]="Entspannt"
TXT[whiskey_4]="Scharfsinnig"
TXT[msg_blurry]="* Deine Sicht verschwimmt etwas... *"
TXT[menu_title]="WÄHLE DEIN SPIEL"
TXT[menu_blackjack]="Blackjack"
TXT[menu_poker]="Texas Hold'em"
TXT[menu_exit]="q) Beenden"
TXT[intro_welcome]="Willkommen im 'Smart Stake Saloon'. Hier gewinnt das Haus... meistens."
TXT[intro_prompt]="Drücke eine Taste, um dein Schicksal zu besiegeln..."
TXT[prompt_balance]="Dein Guthaben"
TXT[prompt_bet]="Einsatz (1-%d), 'r' Regeln, 'q' Ende: "
TXT[msg_initial_deal]="Viel Glück. Du wirst es brauchen."
TXT[msg_both_blackjack]="Beide haben Blackjack! Unentschieden (Push)."
TXT[msg_blackjack_win]="BLACKJACK! Du gewinnst %d€ (3:2)!"
TXT[options_hit]="[H]it"
TXT[options_stand]="[S]tand"
TXT[options_double]="[D]ouble"
TXT[options_surrender]="S[u]rrender"
TXT[options_rules]="[R]egeln"
TXT[prompt_action]="Aktion"
TXT[msg_surrendered]="Du hast aufgegeben. Du erhältst %d€ zurück."
TXT[msg_bust]="Überkauft (Bust)! Du verlierst %d€."
TXT[msg_dealer_turn]="Mal sehen, was ich hier habe..."
TXT[msg_dealer_draw]="Ich ziehe noch eine..."
TXT[msg_dealer_bust]="Dealer überkauft! Du gewinnst %d€."
TXT[msg_win]="Du gewinnst %d€!"
TXT[msg_dealer_win]="Dealer gewinnt mit %d. Du verlierst %d€."
TXT[msg_push]="Unentschieden (Push)."
TXT[msg_search_pockets]="Du durchsuchst deine Taschen... Nichts."
TXT[msg_watch_glimmers]="Deine goldene Uhr glänzt im schummrigen Licht."
TXT[prompt_sell_watch]="Möchtest du deine Uhr für %s50€%s versetzen? [y/n]: "
TXT[msg_sold_watch]="Ein schönes Stück. Ich passe gut darauf auf."
TXT[msg_sold_watch_confirm]="Du hast deine Uhr für 50€ versetzt."
TXT[prompt_buy_whiskey]="Dein Hals ist trocken. Whiskey kaufen für %s10€%s? [y/n]: "
TXT[msg_whiskey_burn]="Ah, das brennt gut."
TXT[msg_game_over]="Du hast alles verloren. Sogar deinen Stolz."
TXT[label_final_balance]="Endguthaben"
TXT[label_max_balance]="Max. Guthaben"
TXT[prompt_exit]="Drücke eine Taste zum Beenden..."
TXT[prompt_next_round]="Drücke eine Taste für die nächste Runde oder 'q' zum Beenden..."
TXT[msg_game_ended]="Spiel beendet. Dein Endguthaben"
TXT[msg_stats_summary]="Deine Bilanz: %s%d Siege%s, %s%d Niederlagen%s, %s%d Unentschieden%s"
TXT[label_high_score]="Höchststand"
TXT[msg_watch_gone]="Und deine Uhr ist weg."
TXT[msg_watch_kept]="Immerhin hast du deine Uhr noch."
TXT[poker_msg_welcome]="Texas Hold'em? Na gut. Schau mir in die Augen."
TXT[poker_msg_deal]="Mal sehen, was der Flop bringt..."
TXT[poker_msg_turn]="Der Turn. Die Spannung steigt."
TXT[poker_msg_river]="Der River. Zeit für die Wahrheit."
TXT[poker_msg_win]="Du gewinnst den Pot von %d€!"
TXT[poker_msg_loss]="Ich gewinne den Pot von %d€."
TXT[poker_msg_push]="Ein Split-Pot. Wir teilen."
TXT[poker_prompt_bet]="Setzen/Mitgehen? (b: setzen, c: check, f: fold, r: regeln): "
TXT[poker_prompt_raise]="Wie viel möchtest du setzen? (1-%d): "
TXT[menu_chuck]="Chuck-a-Luck"
TXT[menu_bandit]="Einarmiger Bandit"
TXT[chuck_msg_welcome]="Chuck-a-Luck? Ein alter Seemanns-Klassiker. Wähle eine Zahl."
TXT[bandit_msg_welcome]="Einarmiger Bandit? Ein Klassiker. Zieh am Hebel!"
TXT[bandit_label_reels]="Walzen"
TXT[bandit_msg_win]="Drei mal %s! Du gewinnst %d€!"
TXT[bandit_msg_win_2]="Zwei mal %s! Du gewinnst %d€!"
TXT[bandit_msg_loss]="Kein Glück diesmal. Probier's nochmal!"
TXT[chuck_prompt_number]="Wähle Zahl (1-6) oder 'r' für Regeln: "
TXT[chuck_prompt_tilt]="Möchtest du den Käfig kippen? (t zum Schummeln, jede andere Taste für Fairplay): "
TXT[chuck_msg_caught]="HEY! Du hast am Käfig gerüttelt!"
TXT[chuck_msg_win_1]="Ein Treffer! Du gewinnst %d€."
TXT[chuck_msg_win_2]="Zwei Treffer! Du gewinnst %d€."
TXT[chuck_msg_win_3]="DREI TREFFER! Wahnsinn! Du gewinnst %d€."
TXT[chuck_msg_loss]="Kein Treffer. Das Haus gewinnt."
TXT[chuck_label_chosen]="Gesetzte Zahl"
TXT[chuck_label_dice]="Würfel"
TXT[poker_hand_0]="High Card"
TXT[poker_hand_1]="Paar"
TXT[poker_hand_2]="Zwei Paare"
TXT[poker_hand_3]="Drilling"
TXT[poker_hand_4]="Straße"
TXT[poker_hand_5]="Flush"
TXT[poker_hand_6]="Full House"
TXT[poker_hand_7]="Vierling"
TXT[poker_hand_8]="Straight Flush"
TXT[poker_hand_9]="Royal Flush"

# Rules
TXT[rules_title]="S P I E L R E G E L N"
TXT[rules_back]="Zurück zum Spiel (Beliebige Taste)"
TXT[rules_blackjack_1]="Ziel: Näher an 21 als der Dealer kommen, ohne zu überkaufen."
TXT[rules_blackjack_2]="Werte: 2-10 = Wert, Bildkarten = 10, Ass = 1 oder 11."
TXT[rules_blackjack_3]="Aktionen: [H]it (Ziehen), [S]tand (Halten), [D]ouble (Verdoppeln),"
TXT[rules_blackjack_4]="          S[u]rrender (Aufgeben für halben Einsatz)."
TXT[rules_blackjack_5]="Blackjack (Ass + 10er) zahlt 3:2."
TXT[rules_poker_1]="Ziel: Beste 5-Karten-Hand aus 2 eigenen und 5 Gemeinschaftskarten."
TXT[rules_poker_2]="Aktionen: [F]old (Aufgeben), [C]heck/Call (Mitgehen), [B]et/Raise."
TXT[rules_poker_3]="Der Dealer geht jeden Raise mit."
TXT[rules_poker_4]="Phasen: Pre-flop, Flop, Turn, River."
TXT[rules_poker_5]="Hand-Rangfolge (Hoch bis Niedrig):"
TXT[rules_poker_rank_1]="Royal Flush|A, K, Q, J, 10 derselben Farbe"
TXT[rules_poker_rank_2]="Straight Flush|5 Karten in Folge derselben Farbe"
TXT[rules_poker_rank_3]="Vierling|4 Karten gleichen Rangs"
TXT[rules_poker_rank_4]="Full House|Ein Drilling und ein Paar"
TXT[rules_poker_rank_5]="Flush|5 Karten derselben Farbe"
TXT[rules_poker_rank_6]="Straße|5 Karten in Folge (verschiedene Farben)"
TXT[rules_poker_rank_7]="Drilling|3 Karten gleichen Rangs"
TXT[rules_poker_rank_8]="Zwei Paare|Zweimal zwei Karten gleichen Rangs"
TXT[rules_poker_rank_9]="Paar|Zwei Karten gleichen Rangs"
TXT[rules_poker_rank_10]="High Card|Die höchste Karte zählt"
TXT[rules_chuck_1]="Ziel: Wette auf eine Zahl (1-6) und wirf drei Würfel."
TXT[rules_chuck_2]="Gewinn: 1 Treffer = 1:1, 2 Treffer = 2:1, 3 Treffer = 10:1."
TXT[rules_chuck_3]="Schummeln: 'Käfig kippen' ('t') erhöht die Gewinnchance,"
TXT[rules_chuck_4]="           birgt aber das Risiko, erwischt zu werden (15%)."
TXT[rules_bandit_1]="Ziel: Drei gleiche Symbole in einer Reihe."
TXT[rules_bandit_2]="Einsatz: Du setzt einen festen Betrag pro Spin."
TXT[rules_bandit_3]="Gewinne: 777 = 50x, ♦♦♦ = 20x, ★★★ = 15x, ✖✖✖ = 10x, ●●● = 5x, ♣♣♣ = 3x."
TXT[rules_bandit_4]="Trostpreis: Zwei gleiche Symbole am Anfang geben 2x Einsatz."
