#!/usr/bin/env bash

# Poker Strings
TXT[menu_poker]="Texas Hold'em"
TXT[poker_msg_welcome]="Texas Hold'em? Na gut. Schau mir in die Augen."
TXT[poker_msg_deal]="Mal sehen, was der Flop bringt..."
TXT[poker_msg_turn]="Der Turn. Die Spannung steigt."
TXT[poker_msg_river]="Der River. Zeit für die Wahrheit."
TXT[poker_msg_win]="Du gewinnst den Pot von %d€!"
TXT[poker_msg_loss]="Ich gewinne den Pot von %d€."
TXT[poker_msg_push]="Ein Split-Pot. Wir teilen."
TXT[poker_prompt_bet]="Setzen/Mitgehen? (b: setzen, c: check, f: fold, r: regeln): "
TXT[poker_prompt_raise]="Wie viel möchtest du setzen? (1-%d): "

TXT[poker_hand_0]="High Card"
TXT[poker_hand_1]="Paar"
TXT[poker_hand_2]="Zwei Paare"
TXT[poker_hand_3]="Drilling"
TXT[poker_hand_4]="Straße"
TXT[poker_hand_5]="Flush"
TXT[poker_hand_6]="Full House"
TXT[poker_hand_7]="Vierling"
TXT[poker_hand_8]="Straight Flush"
TXT[poker_hand_9]="Royal Flush"

# Rules
TXT[rules_poker_1]="Ziel: Beste 5-Karten-Hand aus 2 eigenen und 5 Gemeinschaftskarten."
TXT[rules_poker_2]="Aktionen: [F]old (Aufgeben), [C]heck/Call (Mitgehen), [B]et/Raise."
TXT[rules_poker_3]="Der Dealer geht jeden Raise mit."
TXT[rules_poker_4]="Phasen: Pre-flop, Flop, Turn, River."
TXT[rules_poker_5]="Hand-Rangfolge (Hoch bis Niedrig):"
TXT[rules_poker_rank_1]="Royal Flush|A, K, Q, J, 10 derselben Farbe"
TXT[rules_poker_rank_2]="Straight Flush|5 Karten in Folge derselben Farbe"
TXT[rules_poker_rank_3]="Vierling|4 Karten gleichen Rangs"
TXT[rules_poker_rank_4]="Full House|Ein Drilling und ein Paar"
TXT[rules_poker_rank_5]="Flush|5 Karten derselben Farbe"
TXT[rules_poker_rank_6]="Straße|5 Karten in Folge (verschiedene Farben)"
TXT[rules_poker_rank_7]="Drilling|3 Karten gleichen Rangs"
TXT[rules_poker_rank_8]="Zwei Paare|Zweimal zwei Karten gleichen Rangs"
TXT[rules_poker_rank_9]="Paar|Zwei Karten gleichen Rangs"
TXT[rules_poker_rank_10]="High Card|Die höchste Karte zählt"
