#!/usr/bin/env bash

# Blackjack Strings
TXT[menu_blackjack]="Blackjack"
TXT[msg_initial_deal]="Viel Glück. Du wirst es brauchen."
TXT[msg_both_blackjack]="Beide haben Blackjack! Unentschieden (Push)."
TXT[msg_blackjack_win]="BLACKJACK! Du gewinnst %d€ (3:2)!"
TXT[options_hit]="[H]it"
TXT[options_stand]="[S]tand"
TXT[options_double]="[D]ouble"
TXT[options_split]="S[p]lit"
TXT[options_surrender]="S[u]rrender"
TXT[msg_surrendered]="Du hast aufgegeben. Du erhältst %d€ zurück."
TXT[msg_split]="Hand geteilt! Zwei separate Hände, je %d€ Einsatz."
TXT[msg_split_aces]="Asse geteilt: Jede Hand erhält genau eine Karte und steht dann."
TXT[msg_split_invalid]="Splitten nicht möglich (gleicher Wert, 2 Karten, genug Guthaben erforderlich)."
TXT[label_playing_hand]="Hand %d/%d"
TXT[label_hand_result]="Hand %d:"
TXT[msg_bust]="Überkauft (Bust)! Du verlierst %d€."
TXT[msg_bj_dealer_turn]="Mal sehen, was ich hier habe..."
TXT[msg_dealer_draw]="Ich ziehe noch eine..."
TXT[msg_dealer_bust]="Dealer überkauft! Du gewinnst %d€."
TXT[msg_win]="Du gewinnst %d€!"
TXT[msg_dealer_win]="Dealer gewinnt mit %d. Du verlierst %d€."
TXT[msg_push]="Unentschieden (Push)."

# Rules
TXT[rules_blackjack_1]="Ziel: Näher an 21 als der Dealer kommen, ohne zu überkaufen."
TXT[rules_blackjack_2]="Werte: 2-10 = Wert, Bildkarten = 10, Ass = 1 oder 11."
TXT[rules_blackjack_3]="Aktionen: [H]it (Ziehen), [S]tand (Halten), [D]ouble (Verdoppeln),"
TXT[rules_blackjack_4]="          S[p]lit (Paar teilen), S[u]rrender (Aufgeben für halben Einsatz)."
TXT[rules_blackjack_5]="Blackjack (Ass + 10er) zahlt 3:2. 21 nach Ass-Split zahlt 1:1."
